### ISSUE TITLE
Controller Vibration

### ISSUE THREAD

**Issue by Lu-han-wang** [FRC-Team-620/Warbots2024#27]
Might be a useful resource: https://www.chiefdelphi.com/t/how-to-use-the-rumble-function-on-a-xbox-controller-both-360-and-one-in-java/358167

**Comment by m10653** [comment]
Please Create a Rumble command that allows you to specify the type of rumble, left,right, or both.  Along with how long to rumble.
When you have a draft, create a Pull request, and within the pull request include the words `Closes #27`.

**Comment by singhalasha** [comment]
> Please Create a Rumble command that allows you to specify the type of rumble, left,right, or both. Along with how long to rumble.
> When you have a draft, create a Pull request, and within the pull request include the words `Closes #27`.

Okay, got it 👍🏽

**Comment by Lu-han-wang** [comment]
@singhalasha please review. Some functionalities are missing
