### ISSUE TITLE
Create a baseline auto

### ISSUE THREAD

**Issue by Lu-han-wang** [FRC-Team-620/Warbots2024#40]
- Using the minimum number of sensors
- making a drive auto that crosses the baseline(exits the community)
- set this auto to the default auto(run if no auto is run)

**Comment by London-Grant** [comment]
package frc.robot.commands.drivetrain;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.DriveSubsystem;

public class DriveTime 
{
    private final DriveSubsystem drive;

    private double driveSeconds;
    private ChassisSpeeds drivePower;

    private Timer timer = new Timer();

    public DriveTime(double seconds, ChassisSpeeds power, DriveSubsystem subsystem) {

        driveSeconds = seconds;
        drivePower = power;

        drive = subsystem;

    }

    public void initializeTimer() {

        timer.start();
        timer.reset();

    }

    // This is the big function, what everyone comes for 
    public void autoDrive() {

        drive.drive(drivePower);

    }

    public boolean isFinished() {

        return timer.get() >= driveSeconds;

    }

}

**Comment by m10653** [comment]
#58 closes
