### ISSUE TITLE
Inventory and test game Controllers.

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2024#5]
Currently we have a variety of different game controllers some of them in unknown states of functionality with stickers like "dead" on them that still appear to work.

- [ ] We should go though all our controllers and figure out what ones are still functional and what ones do not work.
- [ ] Also we should go though our controllers and verify all the controller axis's are the same in both ID and direction. We have been running into issues where some of our controllers joysticks are reversed compared to others. We do not want to run into this issue on the field.

**Comment by itsme099** [comment]
controllers tested: 
broken(Red tape): 3
minor issue(yellow tape): 2(joy stick drift)
Working(no tape): 3
