### ISSUE TITLE
Tuning Swerve Drive

### ISSUE THREAD

**Issue by Lu-han-wang** [FRC-Team-620/Warbots2024#69]
- [ ] find the max speed
- [ ] find the max acceleration
- [ ] find max rotation speed/acceleration 

- objective: the robot should accomplish whatever we tell it todo as fast as possible and as accurate as possible

**Comment by m10653** [comment]
#109 addresses  most of this issue.

**Comment by m10653** [comment]
@Lu-han-wang Can we re-open this one. We still have note run the drive at full speed to get the real max values for speed and rotation.
