### ISSUE TITLE
Update Can Ids for Shooter and Intake To follow the Electronics Spreadsheet

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2024#81]
The can ids where changed for the intake and shooter, update the code to follow the Electronics spreadsheet.

**Comment by Lu-han-wang** [comment]
it's all set in bot-bringup branch
should I create a new branch to update main as well?

**Comment by m10653** [comment]
Think we can leave this in the bring up branch as that branch should be merged into main after tomorrow I think

**Comment by m10653** [comment]
Complete
