### ISSUE TITLE
Large number of Smart Dashboard values causing loop overruns

### ISSUE THREAD

**Issue by m10653** [FRC-Team-620/Warbots2024#94]
Currently there is a large amount of data being put into network tables via smart dashboard that is causes performance issues.

These calls should either be trimmed up or only enabled while in a "debug" mode

**Comment by Lu-han-wang** [comment]
k, I'll clean them up sometime today

**Comment by Lu-han-wang** [comment]
done in auto testing branch

**Comment by m10653** [comment]
pull #92 closes
